"""
Build the complete Antigravity recall registry.

After running this:
  @skill-name      → loads that skill as your active context
  @agent-name      → loads that agent persona
  /workflow-name   → runs that workflow
"""

import os
import re

ROOT = r"d:\my-dev-knowledge-base"
AGENT_DIR = os.path.join(ROOT, ".agent", "agents")

# ─── Source directories for skills ────────────────────────────────────────────
SKILL_SOURCES = [
    os.path.join(ROOT, "skills"),
    os.path.join(ROOT, "external-libs", "antigravity-kit", ".agent", "skills"),
]

# ─── Helper: extract frontmatter description ──────────────────────────────────
def get_description(filepath):
    try:
        with open(filepath, 'r', encoding='utf-8', errors='ignore') as f:
            lines = [f.readline() for _ in range(20)]
        for line in lines:
            if line.lower().startswith("description:"):
                d = line.split(":", 1)[1].strip().strip('"\'')
                return d[:120] if len(d) > 120 else d
            m = re.match(r'^#{1,2}\s+(.+)', line)
            if m:
                return m.group(1).strip()[:120]
    except Exception:
        pass
    return ""

# ─── Slugify: convert filename to clean @-recall ID ───────────────────────────
def to_slug(filename):
    name = filename
    name = re.sub(r'\.agent\.md$|\.md$', '', name)
    name = re.sub(r'[^a-zA-Z0-9\-]', '-', name)
    name = re.sub(r'-+', '-', name).strip('-').lower()
    return name

# ─── Create a thin gateway agent for a skill ──────────────────────────────────
def make_skill_gateway(slug, skill_rel_path, description, category="skill"):
    recall_id = f"skill-{slug}" if not slug.startswith("skill") else slug
    filename = f"{recall_id}.agent.md"
    out_path = os.path.join(AGENT_DIR, filename)

    # Don't overwrite existing non-gateway agents
    if os.path.exists(out_path):
        with open(out_path, 'r', encoding='utf-8', errors='ignore') as f:
            existing = f.read(200)
        if "SKILL GATEWAY" not in existing:
            return None  # skip — real agent exists

    content = f"""---
name: '{recall_id}'
target: 'vscode'
infer: true
description: "{description}"
category: skill-gateway
---

<!-- SKILL GATEWAY — auto-generated by scripts/build_recall_registry.py -->

# Skill: {slug}

You are activating the **{slug}** skill context.

## Source
`@[{skill_rel_path}]`

## Description
{description}

## Instructions
Read and apply the full skill file at the path above.
When the user asks for help, apply the skill's guidance and patterns directly.
"""
    with open(out_path, 'w', encoding='utf-8') as f:
        f.write(content)
    return recall_id

# ─── Scan skill directories ───────────────────────────────────────────────────
def scan_skills():
    skills = []
    for src_root in SKILL_SOURCES:
        if not os.path.isdir(src_root):
            continue
        for dirpath, _, filenames in os.walk(src_root):
            for fname in filenames:
                if not fname.endswith('.md'):
                    continue
                # Skip reference sub-files (not top-level skills)
                rel_dir = os.path.relpath(dirpath, src_root)
                depth = len(rel_dir.split(os.sep)) if rel_dir != '.' else 0
                # Only index SKILL.md files and top-level skill files
                if fname == 'SKILL.md' or (depth <= 1 and fname.endswith('.md')):
                    fpath = os.path.join(dirpath, fname)
                    rel = fpath.replace(ROOT + os.sep, './').replace('\\', '/')
                    # Build slug from parent folder name (for SKILL.md) or filename
                    if fname == 'SKILL.md':
                        folder = os.path.basename(dirpath)
                        slug = to_slug(folder)
                    else:
                        slug = to_slug(fname)
                    desc = get_description(fpath)
                    skills.append((slug, rel, desc))
    # Deduplicate by slug — keep first occurrence
    seen = {}
    unique = []
    for slug, rel, desc in skills:
        if slug not in seen:
            seen[slug] = True
            unique.append((slug, rel, desc))
    return sorted(unique, key=lambda x: x[0])

# ─── Ensure workflows have correct naming for / recall ────────────────────────
def audit_workflows():
    wf_dir = os.path.join(ROOT, ".agent", "workflows")
    if not os.path.isdir(wf_dir):
        return []
    wfs = []
    for f in sorted(os.listdir(wf_dir)):
        if f.endswith('.md'):
            slug = to_slug(f)
            wfs.append(slug)
    return wfs

# ─── Generate concise RECALL_SHEET.md cheatsheet ─────────────────────────────
def generate_recall_sheet(skill_count, workflow_slugs, agent_count):
    out = os.path.join(ROOT, "RECALL_SHEET.md")

    # Get fast agents from .agent/agents/
    fast_agents = []
    for f in sorted(os.listdir(AGENT_DIR)):
        if f.endswith('.agent.md'):
            slug = to_slug(f)
            # Only top-level short agents
            if len(slug) <= 12 and '-' not in slug[4:]:
                fast_agents.append(slug)

    # Sample of workflow slugs
    wf_sample = [w for w in workflow_slugs[:30]]

    content = f"""# RECALL SHEET — Antigravity Quick Reference
_Auto-generated — {__import__('datetime').datetime.now().strftime("%Y-%m-%d %H:%M")}_

---

## @ AGENTS  (type @name in chat)

### Fast Mnemonic Agents
| Command | Purpose |
|---------|---------|
| `@alpha` | Ultimate Alpha Beast — transcendent autonomous agent |
| `@react` | React 19.2 frontend expert |
| `@plan` | Project planner & implementaion strategist |
| `@arch` | System architect & ADR writer |
| `@ops` | Terraform / Kubernetes / Infrastructure |
| `@sec` | Security auditor & DevSecOps |
| `@test` | TDD / QA / Playwright expert |
| `@python` | Python / MCP server developer |
| `@orchestrate` | Multi-agent workflow orchestrator |

### All Agents (78+ in registry)
**Location**: `.agent/agents/`  
**Browse**: Open `KNOWLEDGE_INDEX.md` → AGENTS section

**Naming pattern** — agents are grouped by prefix:
| Prefix | Domain |
|--------|--------|
| `@arch-*` | Architecture (ADR, API, blueprint, modernization) |
| `@cloud-azure-*` | Azure IaC (Bicep, Terraform, AVM) |
| `@data-*` | Databases (Postgres, MongoDB, SQL, Power BI) |
| `@dev-*` | Development (debug, janitor, devops, ML, MCP) |
| `@lang-*` | Language specialists (C#, Rust, Go, Java, Python) |
| `@ops-*` | Infrastructure (K8s, GitHub Actions, Terraform) |
| `@plan-*` | Planning (PRD, implementation plan, Jira) |
| `@sec-*` | Security (reviewer, JFrog, StackHawk) |
| `@test-*` | Testing (Playwright, TDD cycle) |
| `@ui-*` | Frontend (React, Next.js, Laravel, Shopify) |
| `@ux-*` | UX (accessibility, designer) |

### Skill Gateway Agents ({skill_count} skills registered)
Skills are now accessible as `@skill-<name>`. Examples:
| Command | Skill |
|---------|-------|
| `@skill-frontend-skills` | Next.js & React frontend patterns |
| `@skill-backend-skills` | FastAPI & Python backend patterns |
| `@skill-kubernetes-resource-optimization-skills` | K8s optimization |
| `@skill-python-ruff-linting-skills` | Python code quality |
| `@skill-compound-engineering` | Plan-Work-Review cycle |
| `@skill-fabric-prompts` | 90 Power BI/Fabric patterns |
| `@skill-notebooklm-mastery` | Advanced NotebookLM research |
| `@skill-x-marketing-expert` | X (Twitter) algorithm expertise |
| `@skill-universal-agentic-frameworks` | Agentic masterclass |
| `@skill-cloud-native-mastery` | Cloud-native orchestration |

---

## / WORKFLOWS  (type /name in chat)

### Key Workflows
| Command | Purpose |
|---------|---------|
| `/plan` | Create implementation plan |
| `/debug` | Systematic root cause analysis |
| `/qa` | End-to-end testing |
| `/deploy` | Production deployment |
| `/orchestrate` | Multi-agent coordination |
| `/create` | Build new application |
| `/audit` | Workspace health check |
| `/brainstorm` | Structured feature exploration |
| `/security-audit` | Security review workflow |
| `/alpha-project-lifecycle` | Full project lifecycle |
| `/alpha-cloud-deployment` | AKS + Dapr + Kafka deploy |
| `/compound-development-cycle` | Plan-Work-Review-Compound |
| `/x-viral-optimizer` | Optimize content for X virality |
| `/fabric-audit` | Power BI BPA remediation |

**All {len(workflow_slugs)} workflows** are in `.agent/workflows/` — type `/` and search.

---

## RECALL SYNTAX REFERENCE

```
# Recall with @
@react                          # Fast mnemonic agent
@arch-adr                       # Named agent from registry
@skill-frontend-skills          # Skill gateway
@[.agent/agents/plan.agent.md]  # Full path (any file)

# Recall with /
/plan                           # Workflow slash command
/debug                          # Debug workflow

# Reference any file in chat
@[path/to/any/file.md]          # Works for ANY file in workspace
@[skills/frontend-skills.md]    # Direct skill reference
@[white-papers/wp6-multi-agent-systems.md]  # White paper reference
```

---

## SEARCH TOOLS

```powershell
# Search by keyword (fast)
.\\scripts\\search.ps1 "react ui" -Type agent
.\\scripts\\search.ps1 "deploy kubernetes" -Type workflow
.\\scripts\\search.ps1 "project management" -Type skill

# Rebuild this index
python scripts/build_recall_registry.py
python scripts/build_index.py
```

---
_Total: {agent_count} agents | {skill_count} skill gateways | {len(workflow_slugs)} workflows_
"""
    with open(out, 'w', encoding='utf-8') as f:
        f.write(content)
    return out

# ─── Main ─────────────────────────────────────────────────────────────────────
if __name__ == "__main__":
    print("[1/3] Scanning skills...")
    skills = scan_skills()
    print(f"      Found {len(skills)} skills")

    print("[2/3] Creating skill gateway agents...")
    created = 0
    skipped = 0
    for slug, rel, desc in skills:
        result = make_skill_gateway(slug, rel, desc)
        if result:
            created += 1
        else:
            skipped += 1

    print(f"      Created: {created}")
    print(f"      Skipped (existing): {skipped}")

    print("[3/3] Generating RECALL_SHEET.md...")
    wf_slugs = audit_workflows()
    agent_count = len([f for f in os.listdir(AGENT_DIR) if f.endswith('.agent.md') and 'gateway' not in open(os.path.join(AGENT_DIR, f), encoding='utf-8', errors='ignore').read(100)])
    sheet_path = generate_recall_sheet(created + skipped, wf_slugs, agent_count)
    print(f"      Written: {sheet_path}")

    print("")
    print("[DONE] Registry complete.")
    print(f"  Skill gateways (@skill-*): {created + skipped}")
    print(f"  Workflows (/name):         {len(wf_slugs)}")
    print(f"  @ Available in chat — type @ or / to browse")
