"""
update_registry.py — Master registry updater.
Runs all 3 steps in sequence:
  1. Fix frontmatter on all agents
  2. Rebuild skill gateway agents
  3. Rebuild KNOWLEDGE_INDEX.md
"""

import os
import sys

# Add scripts dir to path so we can import the other scripts
SCRIPTS_DIR = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(SCRIPTS_DIR)
sys.path.insert(0, SCRIPTS_DIR)

print("=" * 60)
print("  REGISTRY UPDATE — Antigravity Knowledge Base")
print("=" * 60)
print()

# ── STEP 0: Sovereign Consolidation & Purge ──────────────────────────────────
print("[0/3] Running Sovereign Consolidation & Purge...")
try:
    import sovereign_intelligence_consolidation
    sovereign_intelligence_consolidation.main()
    
    import sovereign_intelligence_purge
    sovereign_intelligence_purge.purge_aggressive()
except Exception as e:
    print(f"      Warning: Consolidation/Purge skipped or failed: {e}")
print("      Done.")
print()

# ── STEP 1: Fix frontmatter ────────────────────────────────────────────────────
print("[1/3] Fixing agent frontmatter...")
from cleanup_agent_names import cleanup_frontmatter
cleanup_frontmatter()
print("      Done.")
print()

# ── STEP 2: Rebuild skill gateways ────────────────────────────────────────────
print("[2/3] Rebuilding skill gateway agents...")
import re

BRAIN_DIR = os.path.join(ROOT, ".agent")
AGENT_DIR = os.path.join(BRAIN_DIR, "agents")
SKILLS_DIR = os.path.join(BRAIN_DIR, "skills")
LIBS_DIR = os.path.join(BRAIN_DIR, "libs")

# Automatically find any folder named 'skills' or containing 'SKILL.md' in external-libs and sovereign folders
SKILL_SOURCES = [
    SKILLS_DIR,
    LIBS_DIR,
    os.path.join(BRAIN_DIR, "mcp"),
]

print("      Scanning external repositories for actionable intelligence...")
EXT_LIBS = os.path.join(ROOT, "external-libs")
if os.path.exists(EXT_LIBS):
    for root, dirs, files in os.walk(EXT_LIBS):
        # Add directories named 'skills' 
        if "skills" in [d.lower() for d in dirs]:
            SKILL_SOURCES.append(os.path.join(root, "skills"))
        
        # Add individual files that act as entry points (SKILL.md, instructions.md, etc.)
        # These will be handled by the loop below
        for f in files:
            if f.lower() in ["skill.md", "instructions.md", "prompt.md", "system.md"] or f.endswith(".agent.md"):
                # The directory containing these should be a source
                SKILL_SOURCES.append(root)

# Remove duplicates and normalize
SKILL_SOURCES = list(set([os.path.normpath(p) for p in SKILL_SOURCES]))

def _get_desc(filepath):
    try:
        with open(filepath, 'r', encoding='utf-8', errors='ignore') as f:
            for _ in range(20):
                line = f.readline()
                if line.lower().startswith("description:"):
                    d = line.split(":", 1)[1].strip().strip('"\'')
                    return d[:120] if len(d) > 120 else d
                m = re.match(r'^#{1,2}\s+(.+)', line)
                if m:
                    return m.group(1).strip()[:120]
    except Exception:
        pass
    return ""

def _to_slug(filename):
    name = re.sub(r'\.agent\.md$|\.md$', '', filename)
    name = re.sub(r'[^a-zA-Z0-9\-]', '-', name)
    name = re.sub(r'-+', '-', name).strip('-').lower()
    return name

def _make_gateway(slug, skill_rel_path, description):
    recall_id = f"skill-{slug}" if not slug.startswith("skill") else slug
    filename = f"{recall_id}.agent.md"
    out_path = os.path.join(AGENT_DIR, filename)
    if os.path.exists(out_path):
        try:
            existing = open(out_path, encoding='utf-8', errors='ignore').read(200)
            if "SKILL GATEWAY" not in existing:
                return None
        except Exception:
            pass
    content = f"""---
name: '{recall_id}'
target: 'vscode'
infer: true
description: "{description}"
category: skill-gateway
---

<!-- SKILL GATEWAY — auto-generated by scripts/update_registry.py -->

# Skill: {slug}

## Source
`@[{skill_rel_path}]`

## Description
{description}

## Instructions
Read and apply the full skill file at the source path above.
Apply the skill's guidance and patterns directly to the user's request.
"""
    with open(out_path, 'w', encoding='utf-8') as f:
        f.write(content)
    return recall_id

created = skipped = 0
seen = set()
for src_root in SKILL_SOURCES:
    if not os.path.isdir(src_root): continue
    for dirpath, _, filenames in os.walk(src_root):
        # Avoid recursion into the same source roots if they are nested
        depth = len(os.path.relpath(dirpath, src_root).split(os.sep))
        for fname in sorted(filenames):
            if not fname.endswith('.md'): continue
            
            # Entry point triggers
            is_skill_md = fname.lower() in ('skill.md', 'instructions.md', 'prompt.md', 'system.md')
            is_agent_md = fname.endswith('.agent.md') and "gateway" not in fname
            is_top = depth == 1 and fname.endswith('.md') and fname.lower() not in ('index.md', 'readme.md')
            
            if not (is_skill_md or is_agent_md or is_top): continue
            
            fpath = os.path.join(dirpath, fname)
            rel = fpath.replace(ROOT + os.sep, './').replace('\\', '/')
            
            # Slug generation
            if is_skill_md:
                # Use folder name for SKILL.md
                slug = _to_slug(os.path.basename(dirpath))
                # Exception: if folder is 'skills', use parent or filename
                if slug == "skills":
                    slug = _to_slug(os.path.basename(os.path.dirname(dirpath)))
            else:
                slug = _to_slug(fname)
            
            if slug in seen: continue
            seen.add(slug)
            
            desc = _get_desc(fpath)
            result = _make_gateway(slug, rel, desc)
            if result: created += 1
            else: skipped += 1

print(f"      Created: {created} | Skipped (existing): {skipped}")
print()

# ── STEP 3: Rebuild KNOWLEDGE_INDEX.md ────────────────────────────────────────
print("[3/3] Rebuilding KNOWLEDGE_INDEX.md...")
exec(open(os.path.join(SCRIPTS_DIR, "build_index.py"), encoding='utf-8').read())
print()

print("=" * 60)
print("  DONE — Registry is up to date.")
print("  Open KNOWLEDGE_INDEX.md and Ctrl+F your topic.")
print("  Type @ or / in chat to recall any agent/workflow.")
print("=" * 60)

